var searchData=
[
  ['w_20the_20object_20reference_20count_20message_0',['w the object reference count message',['../_f_m_t2.html#subsubsec_fmt2_dataobject_hdr_msg_refcount',1,'IV.A.2.w. The Object Reference Count Message'],['../_f_m_t3.html#subsubsec_fmt3_dataobject_hdr_msg_refcount',1,'IV.A.2.w. The Object Reference Count Message']]],
  ['wait_1',['wait',['../_v_o_l__connector.html#subsubsecVOLRefReqwait',1,'request: wait'],['../struct_h5_v_l__request__class__t.html#a614f5a3d40d4598ea76af50389048265',1,'H5VL_request_class_t::wait']]],
  ['walk_20through_20the_20error_20stack_2',['Walk through the Error Stack',['../_h5_e__u_g.html#subsubsec_error_ops_walk',1,'']]],
  ['walkerrorstack_3',['walkErrorStack',['../class_h5_1_1_exception.html#a0917968b9c7947fdedbe5541474451a6',1,'H5::Exception']]],
  ['warning_4',['warning',['../_file_lock.html#subsec_filelock_lockdisable_warn',1,'!!! WARNING !!!'],['../md__c_o_d_e___o_f___c_o_n_d_u_c_t.html#autotoc_md16',1,'2. Warning'],['../_thrd_safe.html',1,'HDF5 Threadsafety Warning']]],
  ['warnings_20files_5',['Warnings files',['../md_config_2_r_e_a_d_m_e.html#autotoc_md23',1,'']]],
  ['was_20configured_20with_20a_20needed_20compression_20filter_6',['How to Determine if the HDF5 Library was Configured with a Needed Compression Filter',['../_comp_t_s.html#subsec_compts_notapp_need',1,'']]],
  ['was_20not_20applied_7',['If a Filter Was Not Applied',['../_comp_t_s.html#sec_compts_notapp',1,'']]],
  ['was_20not_20effective_8',['If a Compression Filter Was Not Effective',['../_comp_t_s.html#sec_compts_ineff',1,'']]],
  ['watch_20for_9',['Caveats, Pitfalls, and Things to Watch For',['../_u_n_i_c_o_d_e.html#sec_unicode_warn',1,'']]],
  ['watchme_2emd_10',['WATCHME.md',['../_w_a_t_c_h_m_e_8md.html',1,'']]],
  ['what_20are_20chunks_11',['What are Chunks?',['../hdf5_chunking.html#sec_hdf5_chunking_def',1,'']]],
  ['what_20happens_20if_20the_20library_20runs_20out_20of_20memory_20while_20reading_12',['What happens if the library runs out of memory while reading?',['../_l_b_datatypes.html#subsubsecLBDtypeSpecVLErr',1,'']]],
  ['what_20is_20a_20datatype_13',['What is a Datatype?',['../_l_b_datatypes.html#secLBDtype',1,'']]],
  ['what_20is_20a_20property_20or_20property_20list_14',['What is a Property (or Property List)?',['../_l_b_props_list.html#secLBPList',1,'']]],
  ['what_20is_20in_20an_20hdf5_20file_15',['Discovering what is in an HDF5 file',['../_l_b_contents.html#secLBContents',1,'']]],
  ['what_20types_20of_20scales_20should_20be_20implemented_16',['What types of scales should be implemented?',['../_h5_d_s__u_g.html#subsec_dim_scales_concept_types',1,'']]],
  ['when_20creating_20and_20writing_17',['Applying a Third-party Filter When Creating and Writing',['../_h5_p_l__u_g.html#subsubsec_filter_plugins_model_apply',1,'']]],
  ['when_20deleting_20a_20dataset_18',['Clean up Dimension Scales when deleting a Dataset',['../_h5_d_s__u_g.html#subsubsec_dim_scales_api_model_clean',1,'']]],
  ['when_20using_20custom_20filters_19',['A Word of Caution When Using Custom Filters',['../_h5_p_l__u_g.html#subsubsec_filter_plugins_model_custom',1,'']]],
  ['when_20working_20with_20hdf5_20compressed_20datasets_20',['Improving I/O Performance When Working with HDF5 Compressed Datasets',['../improve_compressed_perf.html',1,'']]],
  ['where_20is_20utf_208_20supported_20in_20hdf5_21',['How and Where Is UTF-8 Supported in HDF5?',['../_u_n_i_c_o_d_e.html#sec_unicode_support',1,'']]],
  ['while_20reading_22',['What happens if the library runs out of memory while reading?',['../_l_b_datatypes.html#subsubsecLBDtypeSpecVLErr',1,'']]],
  ['why_20chunking_23',['Why Chunking ?',['../_l_b_dset_layout.html#susubsecLBDsetLayoutChunkWhy',1,'']]],
  ['why_20file_20locks_24',['Why file locks?',['../_file_lock.html#sec_filelock_why',1,'']]],
  ['will_20not_20be_20modified_25',['Collective, unless target object will not be modified',['../collective_calls.html#sec_collective_calls_nomod',1,'']]],
  ['will_20set_20the_20vol_20connector_26',['Determine How You Will Set The VOL Connector',['../_h5_v_l__u_g.html#subsubsec_vol_quick_set',1,'']]],
  ['windows_27',['Windows',['../md__w_a_t_c_h_m_e.html#autotoc_md415',1,'']]],
  ['windows_20c_20run_20time_20crt_28',['The Windows C Run-time (CRT)',['../freeing_memory.html#sec_freeing_memory_crt',1,'']]],
  ['windows_20driver_29',['The Windows Driver',['../_h5_f__u_g.html#subsubsec_file_alternate_drivers_win',1,'']]],
  ['with_20a_20callback_20function_30',['Traverse an Error Stack with a Callback Function',['../_h5_e__u_g.html#subsubsec_error_ops_travers',1,'']]],
  ['with_20a_20contiguous_20dataset_31',['Creating a New HDF5 File with a Contiguous Dataset',['../_learn_h_d_f_view.html#subsec_learn_hv_topics_file',1,'']]],
  ['with_20a_20dimension_20scale_32',['Attributes of a Dataset with a Dimension Scale',['../_h5_d_s__u_g.html#subsubsec_dim_scales_spec_store_attr',1,'']]],
  ['with_20a_20dimension_20scale_20attached_33',['Extending a Dimension with a Dimension Scale attached',['../_h5_d_s__u_g.html#subsubsec_dim_scales_api_model_extend',1,'']]],
  ['with_20a_20good_20chunking_20strategy_34',['Begin with a good chunking strategy',['../_par_compr.html#subsec_parcompr_perf_begin',1,'']]],
  ['with_20a_20needed_20compression_20filter_35',['How to Determine if the HDF5 Library was Configured with a Needed Compression Filter',['../_comp_t_s.html#subsec_compts_notapp_need',1,'']]],
  ['with_20an_20applied_20third_20party_20filter_36',['Reading Data with an Applied Third-party Filter',['../_h5_p_l__u_g.html#subsubsec_filter_plugins_model_read',1,'']]],
  ['with_20answers_37',['Learning the basics QUIZ with Answers',['../_l_b_quiz_answers.html',1,'LearnBasics']]],
  ['with_20attributes_38',['with attributes',['../_h5__u_g.html#subsubsec_program_model_attr',1,'Working with Attributes'],['../_h5_a__u_g.html#subsec_attribute_work',1,'Working with Attributes']]],
  ['with_20cmake_39',['Compiling an Application with CMake',['../_l_b_compiling.html#secLBCompilingCMake',1,'']]],
  ['with_20cmake_20fetchcontent_40',['HDF5 Building and testing HDF5 VOL connectors with CMake FetchContent',['../_c_make_vols.html',1,'']]],
  ['with_20compressed_20data_41',['How to Use h5dump to Examine Files with Compressed Data',['../_comp_t_s.html#subsubsec_compts_notapp_tools_dump',1,'']]],
  ['with_20different_20languages_42',['APIs vary with different languages',['../_l_b_prog.html#LBProgAPI',1,'']]],
  ['with_20different_20selections_43',['Experiments with Different Selections',['../_l_b_dset_sub_r_w.html#subsecLBDsetSubRWProgExper',1,'']]],
  ['with_20groups_44',['Creating and Working with Groups',['../_h5__u_g.html#subsubsec_program_model_group',1,'']]],
  ['with_20h5ocopy_45',['with h5ocopy',['../copying_committed.html',1,'Copying Committed Datatypes with H5Ocopy'],['../copying_committed.html#sec_copying_committed_datatypes',1,'Copying Committed Datatypes with H5Ocopy']]],
  ['with_20hdf5_46',['with hdf5',['../_getting_started.html',1,'Getting Started with HDF5'],['../_intro_par_h_d_f5.html#subsec_pintro_prog',1,'Parallel Programming with HDF5']]],
  ['with_20hdf5_20compressed_20datasets_47',['Improving I/O Performance When Working with HDF5 Compressed Datasets',['../improve_compressed_perf.html',1,'']]],
  ['with_20hdf5_20tools_48',['Use Case: Examining a JPSS NPP File With HDF5 Tools',['../_view_tools_j_p_s_s.html',1,'']]],
  ['with_20hdfview_49',['Learning HDF5 with HDFView',['../_learn_h_d_f_view.html',1,'']]],
  ['with_20hit_20rate_20threshold_20cache_20size_20reduction_50',['with hit rate threshold cache size reduction',['../_t_n_m_d_c.html#awhrtcsr',1,'Ageout With Hit Rate Threshold Cache Size Reduction'],['../_t_n_m_d_c.html#dawhrtcsr',1,'Ageout With Hit Rate Threshold Cache Size Reduction']]],
  ['with_20initial_20values_51',['Create new Dimension Scale with Initial Values',['../_h5_d_s__u_g.html#subsubsec_dim_scales_api_model_create',1,'']]],
  ['with_20multiple_20hdf5_20files_52',['Working with Multiple HDF5 Files',['../_h5_f__u_g.html#subsec_file_multiple',1,'']]],
  ['with_20no_20access_20property_20list_20parameter_20that_20may_20generate_20metadata_20reads_53',['with no access property list parameter that may generate metadata reads',['../maybe_metadata_reads.html',1,'Functions with No Access Property List Parameter that May Generate Metadata Reads'],['../collective_metadata_io.html#subsubsec_collective_metadata_io_apis_reference_may',1,'Functions with No Access Property List Parameter that May Generate Metadata Reads']]],
  ['with_20other_20hdf5_20library_20versions_54',['Maintaining Compatibility with other HDF5 Library Versions',['../_accessibility.html#CB_MaintainCompat',1,'']]],
  ['with_20phdf5_55',['with phdf5',['../_intro_par_h_d_f5.html#subsec_pintro_create_dset',1,'Creating and Accessing a Dataset with PHDF5'],['../_intro_par_h_d_f5.html#subsec_pintro_create_file',1,'Creating and Accessing a File with PHDF5']]],
  ['with_20swmr_56',['Tools for Working with SWMR',['../_s_w_m_r_t_n.html#subsec_swmr_tools',1,'']]],
  ['with_20the_20file_20access_20property_20list_57',['Example with the File Access Property List',['../_h5_f__u_g.html#subsubsec_file_examples_access',1,'']]],
  ['with_20the_20file_20creation_20property_20list_58',['Example with the File Creation Property List',['../_h5_f__u_g.html#subsubsec_file_examples_props',1,'']]],
  ['with_20the_20hdf_20group_59',['Registering a Filter with The HDF Group',['../_h5_p_l__u_g.html#subsubsec_filter_plugins_prog_reg',1,'']]],
  ['with_20the_20hdf5_20command_20line_20tools_60',['Using VOL Connectors With The HDF5 Command-Line Tools',['../_h5_v_l__u_g.html#subsec_vol_cl',1,'']]],
  ['wk_5freq_61',['wk_req',['../structioc__io__queue__entry__t.html#a67fc76d314482a4560063d0fbc7195e3',1,'ioc_io_queue_entry_t']]],
  ['wk_5fret_62',['wk_ret',['../structioc__io__queue__entry__t.html#a2d5ba2e19e9506553061df08cd19d039',1,'ioc_io_queue_entry_t']]],
  ['wo_5ffapl_5fid_63',['wo_fapl_id',['../struct_h5_f_d__splitter__vfd__config__t.html#ad06759a8e00ff03ee4d78f2aa5016031',1,'H5FD_splitter_vfd_config_t']]],
  ['wo_5fpath_64',['wo_path',['../struct_h5_f_d__splitter__vfd__config__t.html#ae2ff300ccce2d69dba9d6f2a8f20bf4c',1,'H5FD_splitter_vfd_config_t']]],
  ['word_20of_20caution_65',['A Word of Caution',['../_h5_d_o__u_g.html#subsec_hldo_direct_chunk_caution',1,'']]],
  ['word_20of_20caution_20when_20using_20custom_20filters_66',['A Word of Caution When Using Custom Filters',['../_h5_p_l__u_g.html#subsubsec_filter_plugins_model_custom',1,'']]],
  ['working_20with_20attributes_67',['working with attributes',['../_h5_a__u_g.html#subsec_attribute_work',1,'Working with Attributes'],['../_h5__u_g.html#subsubsec_program_model_attr',1,'Working with Attributes']]],
  ['working_20with_20groups_68',['Creating and Working with Groups',['../_h5__u_g.html#subsubsec_program_model_group',1,'']]],
  ['working_20with_20hdf5_20compressed_20datasets_69',['Improving I/O Performance When Working with HDF5 Compressed Datasets',['../improve_compressed_perf.html',1,'']]],
  ['working_20with_20multiple_20hdf5_20files_70',['Working with Multiple HDF5 Files',['../_h5_f__u_g.html#subsec_file_multiple',1,'']]],
  ['working_20with_20swmr_71',['Tools for Working with SWMR',['../_s_w_m_r_t_n.html#subsec_swmr_tools',1,'']]],
  ['wrap_20callbacks_72',['Object Wrap Callbacks',['../_v_o_l__connector.html#subsecVOLRefWrap',1,'']]],
  ['wrap_3a_20free_5fwrap_5fctx_73',['wrap: free_wrap_ctx',['../_v_o_l__connector.html#subsubsecVOLRefWrapfree',1,'']]],
  ['wrap_3a_20get_5fobject_74',['wrap: get_object',['../_v_o_l__connector.html#subsubsecVOLRefWrapobj',1,'']]],
  ['wrap_3a_20get_5fwrap_5fctx_75',['wrap: get_wrap_ctx',['../_v_o_l__connector.html#subsubsecVOLRefWrapctx',1,'']]],
  ['wrap_3a_20unwrap_5fobject_76',['wrap: unwrap_object',['../_v_o_l__connector.html#subsubsecVOLRefWrapunwrap',1,'']]],
  ['wrap_3a_20wrap_5fobject_77',['wrap: wrap_object',['../_v_o_l__connector.html#subsubsecVOLRefWrapwrap',1,'']]],
  ['wrap_5fcls_78',['wrap_cls',['../struct_h5_v_l__class__t.html#a74d541c08c6c71946cc5a1e105ca5e51',1,'H5VL_class_t']]],
  ['wrap_5fobject_79',['wrap_object',['../_v_o_l__connector.html#subsubsecVOLRefWrapwrap',1,'wrap: wrap_object'],['../struct_h5_v_l__wrap__class__t.html#a3b295595ae488978e8afe398ec1507a7',1,'H5VL_wrap_class_t::wrap_object']]],
  ['wrapper_20api_20calls_20for_20passthrough_20connector_20authors_80',['Appendix B Callback Wrapper API Calls for Passthrough Connector Authors',['../_v_o_l__connector.html#secVOLAppB',1,'']]],
  ['wrapper_20errors_20and_20exceptions_81',['Java Wrapper Errors and Exceptions',['../_e_r_r_o_r_s_j_a_v_a.html',1,'']]],
  ['wrappers_82',['Language Wrappers',['../_h5_v_l__u_g.html#subsec_vol_lang',1,'']]],
  ['write_83',['write',['../_v_o_l__connector.html#subsubsecVOLRefAttrwrite',1,'attr: write'],['../thread-safe-lib.html#subsec_tsafe_test_create',1,'Data set create and write'],['../_h5_t__u_g.html#subsubsec_datatype_usage_transfer',1,'Data Transfer (Read and Write)'],['../_v_o_l__connector.html#subsubsecVOLRefDsetwrite',1,'dataset: write'],['../class_h5_1_1_data_set.html#a6dfe8e9cfc09aa8e310c1b36be938245',1,'H5::DataSet::write()'],['../class_h5_1_1_attribute.html#a877df2e3bc187179ed955e086a488442',1,'H5::Attribute::write()'],['../class_h5_1_1_data_set.html#a29ee96c430e40a0060ef45398e4c9e1d',1,'H5::DataSet::write()'],['../struct_h5_f_d__class__t.html#a9a8b074ef365c19c9f757650721dc269',1,'H5FD_class_t::write'],['../struct_h5_v_l__dataset__class__t.html#a85ef69e00e7fa8389d5e021a5a4b5d09',1,'H5VL_dataset_class_t::write'],['../struct_h5_v_l__attr__class__t.html#a0fcaa82af4caaf3197036eaff5a23cb5',1,'H5VL_attr_class_t::write'],['../class_h5_1_1_attribute.html#aa89d50959d01ffc0c7de836cfdf2446f',1,'H5::Attribute::write()']]],
  ['write_20function_84',['write function',['../_h5_d_o__u_g.html#sec_hldo_direct_chunk',1,'Direct Chunk Write Function'],['../_h5_d_o__u_g.html#subsec_hldo_direct_chunk_using',1,'Using the Direct Chunk Write Function']]],
  ['write_20or_20update_20dimension_20scale_20values_85',['Write or Update Dimension Scale values',['../_h5_d_s__u_g.html#subsubsec_dim_scales_api_model_write',1,'']]],
  ['write_20to_20an_20attribute_86',['Steps to create and write to an attribute',['../_intro_h_d_f5.html#subsec_intro_pm_attr',1,'']]],
  ['write_5fselection_87',['write_selection',['../struct_h5_f_d__class__t.html#a522deba44aa79a70d7e96a56c3edf292',1,'H5FD_class_t']]],
  ['write_5fvector_88',['write_vector',['../struct_h5_f_d__class__t.html#a003c382971ac89177c89bbd0b3937b9c',1,'H5FD_class_t']]],
  ['writer_89',['SWMR Writer',['../_s_w_m_r_t_n.html#subsubsec_swmr_model_writer',1,'']]],
  ['writer_20multiple_20reader_20swmr_90',['Introduction to Single-Writer/Multiple-Reader (SWMR)',['../_s_w_m_r_t_n.html',1,'']]],
  ['writer_20multiple_20readers_91',['Single Writer Multiple Readers',['../group___s_w_m_r.html',1,'']]],
  ['writes_92',['writes',['../mod_region_writes.html#sec_mod_region_writes_intro',1,'Introduction to Modified Region Writes'],['../mod_region_writes.html',1,'Modified Region Writes']]],
  ['writing_93',['Applying a Third-party Filter When Creating and Writing',['../_h5_p_l__u_g.html#subsubsec_filter_plugins_model_apply',1,'']]],
  ['writing_20a_20contiguous_20hyperslab_20in_20c_94',['Writing a Contiguous Hyperslab in C',['../_intro_par_cont_hyperslab.html#secIntroParContHyperslabC',1,'']]],
  ['writing_20a_20contiguous_20hyperslab_20in_20fortran_95',['Writing a Contiguous Hyperslab in Fortran',['../_intro_par_cont_hyperslab.html#secIntroParContHyperslabFort',1,'']]],
  ['writing_20a_20filter_20function_96',['Writing a Filter Function',['../_h5_p_l__u_g.html#subsubsec_filter_plugins_prog_write',1,'']]],
  ['writing_20a_20portion_20of_20a_20dataset_97',['Reading and Writing a Portion of a Dataset',['../_h5__u_g.html#subsubsec_program_model_partial',1,'']]],
  ['writing_20an_20attribute_98',['Reading/Writing an attribute',['../_l_b_attr_create.html#secLBAttrCreateRW',1,'']]],
  ['writing_20and_20reading_20attributes_99',['Creating, Writing, and Reading Attributes',['../_h5_a__u_g.html#subsubsec_attribute_work_create',1,'']]],
  ['writing_20by_20chunk_100',['Writing by Chunk',['../_intro_par_chunk.html',1,'IntroParHDF5']]],
  ['writing_20by_20contiguous_20hyperslab_101',['Writing by Contiguous Hyperslab',['../_intro_par_cont_hyperslab.html',1,'IntroParHDF5']]],
  ['writing_20by_20pattern_102',['Writing by Pattern',['../_intro_par_pattern.html',1,'IntroParHDF5']]],
  ['writing_20by_20regularly_20spaced_20data_103',['Writing by Regularly Spaced Data',['../_intro_par_regular_spaced.html',1,'IntroParHDF5']]],
  ['writing_20extendable_20datasets_104',['Creating and Writing Extendable Datasets',['../_h5__u_g.html#subsubsec_program_model_extend',1,'']]],
  ['writing_20or_20reading_20a_20dataset_20to_20or_20from_20a_20file_105',['Writing or Reading a Dataset to or from a File',['../_h5__u_g.html#subsubsec_program_model_data',1,'']]],
  ['writing_20regularly_20spaced_20columns_20in_20c_106',['Writing Regularly Spaced Columns in C',['../_intro_par_regular_spaced.html#secIntroParRegularSpacedC',1,'']]],
  ['writing_20regularly_20spaced_20rows_20in_20fortran_107',['Writing Regularly Spaced Rows in Fortran',['../_intro_par_regular_spaced.html#secIntroParRegularSpacedFort',1,'']]],
  ['writing_20to_20a_20dataset_108',['Reading From and Writing To a Dataset',['../_l_b_dset_r_w.html',1,'LearnBasics']]],
  ['writing_20to_20a_20dataset_20subset_109',['Reading From or Writing To a Dataset Subset',['../_l_b_dset_sub_r_w.html#secLBDsetSubRWSub',1,'']]],
  ['writing_20to_20a_20subset_20of_20a_20dataset_110',['Reading From or Writing To a Subset of a Dataset',['../_l_b_dset_sub_r_w.html',1,'LearnBasics']]],
  ['writing_20to_20or_20reading_20from_20a_20dataset_111',['Writing to or reading from a dataset',['../_intro_h_d_f5.html#subsec_intro_pm_write',1,'']]]
];
