name: arm64 lin

on:
  workflow_dispatch:
  push:
    branches: develop-

jobs:
  arm64:
    runs-on: ubuntu-24.04-arm
    name: arm64 lin
    steps:
      - uses: actions/checkout@v4
      - name: install
        run: |
          sudo apt-get update
          sudo apt-get install -y bison
          sudo apt-get install -y build-essential
          sudo apt-get install -y curl
          sudo apt-get install -y flex
          sudo apt-get install -y git
          sudo apt-get install -y make
          sudo apt-get install -y pbzip2
          sudo apt-get install -y texinfo
          sudo apt-get install -y uuid-runtime
          sudo apt-get install -y zip
      - name: test
        run: |
            mkdir build
            cd build
            cmake \
            -DHDF5_ENABLE_SZIP_SUPPORT:BOOL=OFF \
            -DH5EX_BUILD_EXAMPLES:BOOL=OFF \
            -DBUILDNAME:STRING="-ex" \
            -DCTEST_DROP_SITE_INIT:STRING="my.cdash.org" \
            -DSITE:STRING="ubu-24.arm64" \
            ..
            ctest -D Experimental
