name: cyg ninja ompi -sh

on:
  push:
    branches: [develop]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: git
        run: git config --global core.autocrlf input
      - name: get
        uses: actions/checkout@v4
      - name: set
        uses: cygwin/cygwin-install-action@master
        with:
          packages: cmake gcc-fortran libaec-devel libhwloc-devel libevent-devel make ninja openmpi libopenmpi-devel perl zlib-devel
      - name: test
        run: |
          export PATH=/usr/bin:$PATH
          mkdir build
          cd build
          cmake -G Ninja \
           -DBUILDNAME:STRING="ninja/ompi/-sh" \
           -DBUILD_SHARED_LIBS:BOOL=OFF \
           -DCMAKE_BUILD_WITH_INSTALL_RPATH=TRUE \
           -DCMAKE_C_COMPILER=/usr/bin/mpicc \
           -DCMAKE_CXX_COMPILER=/usr/bin/mpicxx \
           -DCTEST_DROP_SITE_INIT:STRING="my.cdash.org" \
           -DHDF5_ENABLE_PARALLEL:BOOL=ON \
           -DSITE:STRING=cyg \
           ..
          ctest -D Experimental
        shell: C:\cygwin\bin\bash.exe -eo pipefail -o igncr '{0}'
