name: i386 alp d  f

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup alpine
        uses: jirutka/setup-alpine@v1
        with:
          arch: x86
          packages: >
            build-base
            libgit2-dev
            cmake
            gfortran
      - name: run script
        run: |
          mkdir build
          cd build
          cmake \
            -DBUILDNAME:STRING="d/f" \
            -DCMAKE_BUILD_TYPE=Debug \
            -DHDF5_BUILD_FORTRAN=ON \
            -DCTEST_DROP_SITE_INIT:STRING="my.cdash.org" \
            -DCTEST_DROP_LOCATION_INIT="/submit.php?project=HDF5" \
            -DSITE:STRING=alp.i386 \
             ..
#          ctest -D Experimental
        shell: alpine.sh --root {0}
