name: lin nvhpc -wa -we

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install
        run: |
          sudo apt update
          sudo apt install -y cmake libzip-dev
      - name: free
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          tool-cache: false
          swap-storage: true
      - name: nvhpc
        run: |
          curl https://developer.download.nvidia.com/hpc-sdk/ubuntu/DEB-GPG-KEY-NVIDIA-HPC-SDK | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-hpcsdk-archive-keyring.gpg
          echo 'deb [signed-by=/usr/share/keyrings/nvidia-hpcsdk-archive-keyring.gpg] https://developer.download.nvidia.com/hpc-sdk/ubuntu/amd64 /' | sudo tee /etc/apt/sources.list.d/nvhpc.list
          sudo apt-get update -y
          sudo apt-get install -y nvhpc-25-9
      - name: get
        uses: actions/checkout@v5
      - name: test
        env:
          FC: nvfortran
          CC: nvc
          FCFLAGS: -fPIC -O3
          CFLAGS: -fPIC -O3
        run: |
          export NVHPCSDK=/opt/nvidia/hpc_sdk
          export OMPI_CXX=/opt/nvidia/hpc_sdk/Linux_x86_64/25.9/compilers/bin/nvc++
          export OMPI_CC=/opt/nvidia/hpc_sdk/Linux_x86_64/25.9/compilers/bin/nvc
          export OMPI_FC=/opt/nvidia/hpc_sdk/Linux_x86_64/25.9/compilers/bin/nvfortran
          export LD_LIBRARY_PATH=/opt/nvidia/hpc_sdk/Linux_x86_64/25.9/cuda/13.0/lib64:/opt/nvidia/hpc_sdk/Linux_x86_64/25.9/compilers/lib
          export PATH=/opt/nvidia/hpc_sdk/Linux_x86_64/25.9/comm_libs/hpcx/bin:/opt/nvidia/hpc_sdk/Linux_x86_64/25.9/compilers/bin:$PATH
          mkdir build
          cd build
          cmake \
          -DBUILDNAME="nvhpc-25.9/-wa/-we" \
          -DCTEST_DROP_SITE_INIT=my.cdash.org \
          -DHDF5_WANT_DATA_ACCURACY=OFF \
          -DHDF5_WANT_DCONV_EXCEPTION=OFF \
          -DSITE:STRING="ubu-24" \
          ..
          ctest -D Experimental
