name: lin nvhpc

on:
  workflow_dispatch:
  push:
    branches: [ develop- ]
    paths-ignore:
      - '.github/CODEOWNERS'
      - '.github/FUNDING.yml'
      - 'doc/**'
      - 'release_docs/**'
      - 'ACKNOWLEDGEMENTS'
      - 'COPYING**'
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.sha || github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install System dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake libzip-dev
      - name: Install NVHPC
        run: |
          curl https://developer.download.nvidia.com/hpc-sdk/ubuntu/DEB-GPG-KEY-NVIDIA-HPC-SDK | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-hpcsdk-archive-keyring.gpg
          echo 'deb [signed-by=/usr/share/keyrings/nvidia-hpcsdk-archive-keyring.gpg] https://developer.download.nvidia.com/hpc-sdk/ubuntu/amd64 /' | sudo tee /etc/apt/sources.list.d/nvhpc.list
          sudo apt-get update -y
          sudo apt-get install -y nvhpc-24-9
      - name: Get Sources
        uses: actions/checkout@v4
      - name: Test HDF5
        env:
          FC: nvfortran
          CC: nvc
          CFLAGS: -fPIC
          FCFLAGS: -fPIC
        run: |
          export NVHPCSDK=/opt/nvidia/hpc_sdk
          export OMPI_CXX=/opt/nvidia/hpc_sdk/Linux_x86_64/24.9/compilers/bin/nvc++
          export OMPI_CC=/opt/nvidia/hpc_sdk/Linux_x86_64/24.9/compilers/bin/nvc
          export OMPI_FC=/opt/nvidia/hpc_sdk/Linux_x86_64/24.9/compilers/bin/nvfortran
          export LD_LIBRARY_PATH=/opt/nvidia/hpc_sdk/Linux_x86_64/24.9/cuda/12.3/lib64:/opt/nvidia/hpc_sdk/Linux_x86_64/24.9/compilers/lib
          export PATH=/opt/nvidia/hpc_sdk/Linux_x86_64/24.9/comm_libs/openmpi4/bin:/opt/nvidia/hpc_sdk/Linux_x86_64/24.9/compilers/bin:$PATH        
          cmake \
          -D BUILD_SHARED_LIBS:BOOL=OFF \
          -D CTEST_DROP_SITE_INIT:STRING="my.cdash.org" \
          -D SITE:STRING=ubu ..
           ctest -T Build  -j
           ctest -T Test  -j	  
