name: mac Xcode

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
    
jobs:
  build:
    name: Generate Xcode project
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: brew install curl openssl libaec
      - name: Generate Xcode project
        run: |
          export OPENSSL_ROOT_DIR=/usr/local/Cellar/openssl@3/3.1.1
          mkdir build
          cd build
          cmake -DHDF5_ENABLE_SZIP_SUPPORT:BOOL=OFF -G Xcode ..
          cmake --build . --config Release
          ctest --test-dir . -C Release
          sudo cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_INSTALL_CONFIG_NAME=Release -P cmake_install.cmake
          