name: s390x lin mpich

on:
  push:
    branches:
      - develop-

jobs:
  s390x_job:
    name: s390x lin
    runs-on: ubuntu-latest

    steps:
      - name: Get Sources
        uses: actions/checkout@v4

      - name: Run
        uses: uraimo/run-on-arch-action@v3
        id: runcmd
        with:
          arch: s390x
          distro: ubuntu_latest
          install: |
            apt-get update -q -y
            apt-get install -q -y git cmake libjpeg-dev zlib1g zlib1g-dev
            apt-get install -q -y gfortran g++  yacc flex libtool autotools-dev
            apt-get install -q -y mpich
          run: |
            mkdir build
            cd build
            cmake \
            -D BUILDNAME:STRING="mpich" \
            -D CTEST_DROP_SITE_INIT:STRING="my.cdash.org" \
            -D HDF5_ENABLE_PARALLEL:BOOL=ON \
            -D SITE:STRING=s390x \
            ..
            ctest -D Experimental
