name: win ninja llvm icx

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: ninja
        uses: lukka/get-cmake@latest    
      - name: llvm
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "18"
      - name: icx
        uses: awvwgk/setup-fortran@main
        with:
          compiler: intel
          version: '2025.0'
      - name: checkout
        uses: actions/checkout@v4
      - name: set
        shell: cmd
        run: |
          "C:\Program Files (x86)\Intel\oneAPI\setvars.bat"
      - name: test
        shell: cmd
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_C_COMPILER="C:/Program Files (x86)/Intel/oneAPI/compiler/latest/bin/icx.exe" -DCMAKE_CXX_COMPILER="C:/Program Files (x86)/Intel/oneAPI/compiler/latest/bin/icpx.exe" -DCMAKE_Fortran_COMPILER="C:/Program Files (x86)/Intel/oneAPI/compiler/latest/bin/ifx.exe" -DBUILD_SHARED_LIBS:BOOL=OFF  -DHDF5_BUILD_FORTRAN:BOOL=OFF  -DHDF5_ENABLE_PARALLEL:BOOL=OFF  -DHDF5_ENABLE_Z_LIB_SUPPORT:BOOL=OFF -DHDF5_ENABLE_SZIP_SUPPORT:BOOL=OFF -DHDF5_ENABLE_SUBFILING_VFD:BOOL=OFF -DCTEST_DROP_SITE_INIT=my.cdash.org -DCTEST_DROP_LOCATION_INIT="/submit.php?project=HDF5" -DSITE=win -DBUILDNAME="ninja/icx" ..
          ctest -D Experimental
